name: CI

on:
  push:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and run tests
      run: |
        docker-compose build angular-test
        docker-compose run --rm angular-test
